In [1]:
import tensorflow as tf
import numpy as np

In [4]:
dataset=tf.data.Dataset.range(10)

In [8]:
for element in dataset.as_numpy_iterator():
  print(element)

0
1
2
3
4
5
6
7
8
9


In [5]:
window_=dataset.window(5, shift=1, drop_remainder=True)

In [6]:
for element in window_:
    for val in element:
        print(val.numpy(), end='')
    print()

01234
12345
23456
34567
45678
56789


In [41]:
flat=window_.flat_map(lambda window: window.batch(5))

In [46]:
for window in window_:
    for val in window:
        print(val.numpy(), end='')
    print()

01234
12345
23456
34567
45678
56789


In [48]:
for window in flat:
    print(window.numpy())
    

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [52]:
map=flat.map(lambda window: (window[:-1], window[-1:]))



<PrefetchDataset shapes: ((None, None), (None, None)), types: (tf.int64, tf.int64)>

In [59]:
map.shuffle(buffer_size=10)

<ShuffleDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>

In [76]:
batch=map.batch(2).prefetch(1)

In [77]:
for x, y in batch:
    print("x= ", x.numpy())
    print("y= " , y.numpy())

x=  [[0 1 2 3]
 [1 2 3 4]]
y=  [[4]
 [5]]
x=  [[2 3 4 5]
 [3 4 5 6]]
y=  [[6]
 [7]]
x=  [[4 5 6 7]
 [5 6 7 8]]
y=  [[8]
 [9]]


In [3]:
dataset.window(5)

NameError: name 'dataset' is not defined